### ISSUE TITLE
Public schema admin cant be accessed

### ISSUE THREAD

**Issue by RoadRunner11** [Corvia/django-tenant-users#60] opened 2020-09-14 19:08 UTC
I have correctly set up the system, but whenever I tried to login on my public schema admin page it constantly redirects me back to the login page. 
How can I use the admin multi site to solve this issue, cos it was mentioned in the doc that one can only use admin with admin multisite.

**Comment by Viatrak** [comment] 2020-10-06 16:35
Closing due to lack of information.

**Closed by Viatrak** 2020-10-06 16:35 UTC

**Comment by BarryMolina** [comment] 2022-09-05 15:46
Encountered this exact same problem, caused by prematurely setting "SESSION_COOKIE_DOMAIN" as recommended in the installation instructions

**Comment by Dresdn** [comment] 2022-09-05 19:08
> prematurely

What do you mean by this? Setting `SESSION_COOKIE_DOMAIN` before doing the rest of the install caused issues and it wasn't only until everything was done that you could set this variable?

Is this a documentation update that needs to happen, or what could be modified/updated to help?

**Comment by theopoenaru** [comment] 2022-10-05 02:51
thanks @BarryMolina! had the same issue and this fixed it

@Dresdn I set up the project (including `SESSION_COOKIE_DOMAIN = '.localhost:8000'`), migrated the models, created a public tenant and user, but when I tried logging into the admin site it would do nothing (enter user/pwd, press login, page just refreshes). However, once I commented out `SESSION_COOKIE_DOMAIN` I was able to login.

**Comment by Dresdn** [comment] 2022-10-05 04:16
@theopoenaru - Cookies don't support port numbers, so I would bet your `SESSION_COOKIE_DOMAIN` was incorrect, causing the session cookie to not be valid (logging into the admin site, `foo.localhost`, or `bar.localhost` would all have an issue).

I would bet if you set it to `SESSION_COOKIE_DOMAIN = '.localhost'`, that would have worked.

Did you reference some documentation saying to use the port number? Curious if anything needs to be updated.
