### ISSUE TITLE
Migration Fails Using Pyscopg3 and Django 4

### ISSUE THREAD

**Issue by Johncs2d** [Corvia/django-tenant-users#434] opened 2023-06-14 09:28 UTC
When Using psycopg3, django makemigrations will raise a RecursionError: maximum recursion depth exceeded while calling a Python object

snippet of the error:

` File "/home/jab/.cache/pypoetry/virtualenvs/backstagecore-Ljq23cFS-py3.10/lib/python3.10/site-packages/django/db/backends/utils.py", line 119, in debug_sql
    sql = self.db.ops.last_executed_query(self.cursor, sql, params)
  File "/home/jab/.cache/pypoetry/virtualenvs/backstagecore-Ljq23cFS-py3.10/lib/python3.10/site-packages/django/db/backends/postgresql/operations.py", line 312, in last_executed_query
    return self.compose_sql(sql, params)
  File "/home/jab/.cache/pypoetry/virtualenvs/backstagecore-Ljq23cFS-py3.10/lib/python3.10/site-packages/django/db/backends/postgresql/operations.py", line 205, in compose_sql
    return mogrify(sql, params, self.connection)
  File "/home/jab/.cache/pypoetry/virtualenvs/backstagecore-Ljq23cFS-py3.10/lib/python3.10/site-packages/django/db/backends/postgresql/psycopg_any.py", line 21, in mogrify
    with connection.cursor() as cursor:
  File "/home/jab/.cache/pypoetry/virtualenvs/backstagecore-Ljq23cFS-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/jab/.cache/pypoetry/virtualenvs/backstagecore-Ljq23cFS-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 330, in cursor
    return self._cursor()
  File "/home/jab/.cache/pypoetry/virtualenvs/backstagecore-Ljq23cFS-py3.10/lib/python3.10/site-packages/django_tenants/postgresql_backend/base.py", line 171, in _cursor
    cursor_for_search_path.execute('SET search_path = {0}'.format(','.join(formatted_search_paths)))
  File "/home/jab/.cache/pypoetry/virtualenvs/backstagecore-Ljq23cFS-py3.10/lib/python3.10/site-packages/django/db/backends/utils.py", line 101, in execute
    with self.debug_sql(sql, params, use_last_executed_query=True):
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)`

## Expected Behavior
Migration Should Succeed

## Actual Behavior
Migration is not proceeding with pyscopg3 but it's working with pyscopg2

## Your Environment
ubuntu in wsl2

* Version used:
Django v4
pyscopg3
python 3.10.6

ubuntu 20

**Comment by Dresdn** [comment] 2023-06-15 14:38
Seems like something with your pyscopg3 install isn't correct.

To quickly check, from this project, I updated to Django 4.2, modified the `pyscopg2-binary` dependency to be `psycopg = {version = "^3.1.9", extras = ["binary"]}`, and then ran the test suite.

Everything migrated and tested as expected.

**Comment by Dresdn** [comment] 2023-07-09 19:55
Any update @Johncs2d?

**Comment by tomturner** [comment] 2023-07-10 11:42
The problem is I have yet to do the work on Django Tenants to allow for psycopg 3

I will do it soon however I am very busy at the moment.  I do welcome pull requests.

please see.

https://github.com/django-tenants/django-tenants/issues/948

**Comment by Dresdn** [comment] 2024-01-20 19:55
Closing as seems to be resolved in https://github.com/django-tenants/django-tenants/releases/tag/v3.6.1

**Closed by Dresdn** 2024-01-20 19:55 UTC
